# Generated by Django 3.1.5 on 2022-02-11 11:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blog_title', models.CharField(blank=True, max_length=150, null=True)),
                ('blog_description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='hakkimizdaBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hakkimizda', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Hakkımızda Yazı',
            },
        ),
        migrations.CreateModel(
            name='newsletterBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'E-Bulten',
            },
        ),
        migrations.CreateModel(
            name='settingBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('setting_adress', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_email', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_linkedin', models.CharField(blank=True, max_length=1000, null=True)),
                ('setting_footer_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Website Ayarları',
            },
        ),
        migrations.CreateModel(
            name='systemImageBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Sistem Görselleri',
            },
        ),
        migrations.CreateModel(
            name='userBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.CharField(blank=True, max_length=150, null=True)),
                ('user_number', models.CharField(blank=True, max_length=150, null=True)),
                ('user_message', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'User Gelen Bilgiler',
            },
        ),
    ]
