# Generated by Django 3.1.5 on 2022-02-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogbilgi',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.blogcategory'),
        ),
    ]
