# Generated by Django 3.1.5 on 2022-02-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_referencecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferanceBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referance_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('referance_title', models.CharField(blank=True, max_length=150, null=True)),
                ('referance_description', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.referencecategory')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
