# Generated by Django 3.1.5 on 2022-02-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220211_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterbilgi',
            name='surname',
        ),
        migrations.AddField(
            model_name='newsletterbilgi',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
