# Generated by Django 3.1.5 on 2022-02-11 13:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_hizmetlerimizcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmetlerimiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.hizmetlerimizcategory')),
            ],
        ),
    ]
