# Generated by Django 3.1.5 on 2022-02-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_hizmetlerimiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hizmetlerimiz',
            old_name='description',
            new_name='hizmet_description',
        ),
        migrations.RenameField(
            model_name='hizmetlerimiz',
            old_name='name',
            new_name='hizmet_title',
        ),
    ]
