# Generated by Django 3.2.7 on 2022-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20220222_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimagebilgi',
            name='banner_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='systemimagebilgi',
            name='banner_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
