# Generated by Django 3.2.7 on 2022-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220222_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurumsalBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurumsal_title', models.CharField(blank=True, max_length=150, null=True)),
                ('kurumsal_description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kurumsal',
            },
        ),
    ]
