# Generated by Django 3.2.7 on 2022-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_kurumsalbilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='avukatlarimiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_title', models.CharField(blank=True, max_length=150, null=True)),
                ('lawyer_area', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
