# Generated by Django 3.2.7 on 2022-02-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_avukatlarimiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='avukatlarimiz',
            new_name='avukatBilgi',
        ),
    ]
