# Generated by Django 3.2.7 on 2022-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_hizmetlerimiz_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', null=True, upload_to=''),
        ),
    ]
