# Generated by Django 3.2.7 on 2022-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_hizmetlerimiz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbilgi',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
