# Generated by Django 3.2.7 on 2022-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_blogbilgi_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurumsalbilgi',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='avukatbilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogbilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hakkimizdabilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='referancebilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='settingbilgi',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemimagebilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userbilgi',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
    ]
