# Generated by Django 3.2.7 on 2022-02-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20220223_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avukatBilgi',
        ),
    ]
