# Generated by Django 3.1.5 on 2022-03-02 08:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20220302_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizdabilgi',
            name='hakkimizda_german',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
