# Generated by Django 3.1.5 on 2022-03-02 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_hakkimizdabilgi_hakkimizda_german'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmetlerimiz',
            name='hizmet_description_german',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlerimiz',
            name='hizmet_title_german',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hizmetlerimizcategory',
            name='name_german',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
