# Generated by Django 3.1.5 on 2022-03-09 06:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20220302_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimagebilgi',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='systemimagebilgi',
            name='banner_description_german',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
