# Generated by Django 3.1.5 on 2022-03-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hizmetlerimiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hizmetlerimiz', to='website.hizmetlerimizcategory'),
        ),
    ]
