# Generated by Django 3.2.7 on 2022-07-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20220321_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogbilgi',
            name='category',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='hakkimizdaBilgi',
        ),
        migrations.RemoveField(
            model_name='hizmetlerimiz',
            name='category',
        ),
        migrations.DeleteModel(
            name='kurumsalBilgi',
        ),
        migrations.DeleteModel(
            name='newsletterBilgi',
        ),
        migrations.RemoveField(
            model_name='referancebilgi',
            name='category',
        ),
        migrations.DeleteModel(
            name='settingBilgi',
        ),
        migrations.DeleteModel(
            name='systemImageBilgi',
        ),
        migrations.DeleteModel(
            name='userBilgi',
        ),
        migrations.DeleteModel(
            name='blogBilgi',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='Hizmetlerimiz',
        ),
        migrations.DeleteModel(
            name='HizmetlerimizCategory',
        ),
        migrations.DeleteModel(
            name='ReferanceBilgi',
        ),
        migrations.DeleteModel(
            name='ReferenceCategory',
        ),
    ]
